#!/bin/bash
echo "Install i3"

sudo apt-get install pcmanfm xterm rxvt-unicode zsh htop feh

cd xcwd && make && sudo make install && cd - > /dev/null

# URXVT section
cp /etc/inputrc ~/.inputrc
cp Xresources ~/.Xresources
xrdb ~/.Xresources
mkdir ~/.urxvt/ext
cp -r ext/urxvt-perls/keyboard-select ~/.urxvt/ext/



/usr/lib/apt/apt-helper download-file http://dl.bintray.com/i3/i3-autobuild-ubuntu/pool/main/i/i3-autobuild-keyring/i3-autobuild-keyring_2016.10.01_all.deb keyring.deb SHA256:460e8c7f67a6ae7c3996cc8a5915548fe2fee9637b1653353ec62b954978d844
sudo apt install ./keyring.deb
sudo rm ./keyring.deb
echo 'deb http://dl.bintray.com/i3/i3-autobuild-ubuntu xenial main' > ./i3-autobuild.list
sudo cp ./i3-autobuild.list /etc/apt/sources.list.d/i3-autobuild.list
sudo  apt update
sudo apt install i3

rsync ./config ~/.config/i3/config

