#!/bin/bash

cp $HOME/.bashrc ./bashrc.bak
cp bashrc $HOME/.bashrc

cd ..;CURRPATH=`pwd`; cd - > /dev/null

BASHDIR=$HOME/.bashrc.d
mkdir -p $BASHDIR 
BASHUTIL=$BASHDIR/bashrc.utils
echo "" > $BASHUTIL
echo "export PATH=\$PATH:${CURRPATH}/bin:${CURRPATH}/R" >> $BASHUTIL
# autojump configuration
echo 'export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND ;} history -a"' >> $BASHUTIL
echo '. /usr/share/autojump/autojump.sh' >> $BASHUTIL
chmod 755 $BASHUTIL

cp git-completion.bash $BASHDIR
chmod 755 $BASHDIR/git-completion.bash

echo "BASHRC SETTING DONE"

