#!/bin/bash

cp $HOME/.bashrc ./bashrc.bak
cp bashrc $HOME/.bashrc

cd ..;CURRPATH=`pwd`; cd - > /dev/null

mkdir -p $HOME/.bashrc.d
BASHUTIL=$HOME/.bashrc.d/bashrc.utils
echo "" > $BASHUTIL
echo "export PATH=\$PATH:${CURRPATH}/bin:${CURRPATH}/R" >> $BASHUTIL
chmod 755 $HOME/.bashrc.d/bashrc.utils


echo "BASHRC SETTING DONE"

