#!/usr/bin/env Rscript
library(data.table)


#rload("ref.txt")
source(rload,"ref.txt",local=TRUE)

load(stat.rData)

print(avg)
print(min_)
print(max_)
print(sd_)


rload log.txt
load(stat.rData)

print(avg)
print(min_)
print(max_)
print(sd_)
