#!/usr/bin/env Rscript
library(data.table)

initial.options <- commandArgs(trailingOnly = FALSE)
file.arg.name <- "--file="
script.name <- sub(file.arg.name, "", initial.options[grep(file.arg.name, initial.options)])
script.basename <- dirname(script.name)
rload.path <- paste(sep="/", script.basename, "rload")
print(paste("Sourcing",rload.path,"from",script.name))


#rload("ref.txt")
commandArgs <- function(trailingOnly) "ref.txt"
source(rload.path,local=TRUE,echo=FALSE)

load("data_out.RData")

print("read")
print(avg)
print(min_)
print(max_)
print(sd_)


commandArgs <- function(trailingOnly) "log.txt"
source(rload.path,local=TRUE,echo=FALSE)
load("data_out.RData")

print(avg)
print(min_)
print(max_)
print(sd_)
