#!/usr/bin/env Rscript
library(data.table)

args = commandArgs(trailingOnly=TRUE)

# test if there is at least one argument: if not, return an error
if (length(args)==0) {
  stop("At least one argument must be supplied (input file).n", call.=FALSE)
} 
if (length(args)<=1) {
  # default output file
  args[2] = "data_out.RData"
} 
if (length(args)<=2) {
  head = FALSE
}
if ( args[1] == "--help") {
  message("arg1: input file name")
  message("arg2: output file name (default: data_out.RData)")
  message("arg3: header flag (default: FALSE)")
  q()
}

head

data_out = fread("test.txt")
#data_out = read.csv(file="test.txt",header=head)
data_out


wd = getwd()
print(wd)

save(data_out,file=args[2])

