#!/bin/bash

sed -i 's/-lflite"/-lflite -lasound"/' configure && ./configure --prefix=/usr --enable-gpl --enable-version3 --enable-nonfree --disable-static --enable-shared --disable-debug --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --docdir=/usr/share/doc/ffmpeg-3.4.1 && make && gcc tools/qt-faststart.c -o tools/qt-faststart


